[package]
name = "crow"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
rusqlite = { version = "0.29", features = ["bundled"] }
sha2 = "0.10"
anyhow = "1.0"
